language: ruby
node_js:
  - "6.1.0"
python:
  - '2.7'
rvm:
  - 2.0.0
notifications:
  email:
    - tang.jilong@gmail.com
before_script:
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - sudo pip install fabric
  - bundle install
  - npm install
  - npm install -g grunt-cli
script:
  - echo 'Build Assets Files.'
  - grunt
  - echo 'Build Entire Site.'
 # - sed 's/production_env: false/production_env: true/g' _config.yml > _config_production.yml
  - bundle exec jekyll build
after_success:
  - echo 'Ready to deploy distro to Linode server.'
  - fab setup deploy
  - echo 'Deploy entire site to Linode server finished!!!'
branches:
  only:
  - master
env:
  global:
    - secure: "aH1zSdgeddHqkbAST3Exva1vfMpoYUrL9uGg64YGxT06snYDXh1AcF25Cro2fshcP1cmx9jZThnCzjAguJGCQ8IK+TyTP/9xZGexI1z8i3w6tMyayKTRdIxpYeNxpQlaZJ1ew7S7N8T4IdiLUvJ9I4BfSLviJB0NNxYFd6wjJvo="
    - secure: "AeExhiTlXE+jQItDcWK+pS0K+oSuMZSyV4w45HmjOZzxaSLqIiplGOZui/CwX0kE+QoBUc+dmuSAwBEgCHErRwN+oHRQHz1B5cFcM8pygKP9bAFZOQMjXZHI50soPu8MFWz0AP+XqKPOnDS1kWSIqZSRaA/VU25A5zqRgmGyW3U="
    - secure: "E7k3crEN+YHjIjgDZ1G56xyPoWENlKQROe5qlaa2sBVxERdbAztNPZJ2tHzMA/Kwyp0ejujCrg0mXml8bFQL1g7ZMaoazZ+L3tTrPP/feUyG+bbDvYHGW95amAusJdpEVOsxe1AhGURTgbCrf0ODefX0oZKgpUF3r49omk/s/Z8="
    - secure: "jxuJAOvswMv2rWzhqgcZPl68BfrfmiJ/J4YcebqCRf9uWS/KAL82Da0iR0CVaOxPyax6RPmEaR48ZiHWE1TOSwNNA2rc/sr+P1whP9sH6mGn5Xew06YBlMvk2gF27NG7m8wKG1Tlpsp3m/yc2r8SJzNWVzthobVr66FAWfFRyAc="
    - secure: "iUmgi+BoeK8ABpqn+TPp1oMIMsgLGc6RBdZJl3Nr0wsJRvVPQ9Cb0NMqu6JuJZ7lWS0HmgSeqnFT9PPLzlMDGmRWtQALGRG71uFyawaJGP9uPddGkSOMfC6SdJd595SbApa8TMxNwUGCBjxjLflMlqVuWdtmmbsIPQJzCslSkVA="
    - secure: "NGezav4SPOmXmr2zfMJP+ndcXvFgz9v9g9nP5aoq0VhaR+G6StnRCR3WjP9BkxLcf7EJK+sQkMQDrOFbK5i2foMi6mmFIgyQynl30b07rivHLH4G6NFzGygeTxn3X9xbZiTgcIheE3s3M5d2FZJznX+fXm8Ntfaj/tBg1plqHYM="
    - secure: "HxzY9LphVwTBVacBD/P6bkUs11Tsklejh84i9SjDujhNJEnTEsrnzbGtTXIj7MQrauEkd7j42uNJdsAL8kmN38Wwj3HaXfG3AJVet1rriBG7OVe1ChAu/5dgqLlwxL4jOxrh3NMPwKeuqCxbMjYURd48FlHio2x8dmXDxZgq5RI="
    - secure: "Ilv9En4/memeJOhZsIyKc8pUR0DB88+V3JoaSNNpIsPWU0z6YM4mL+lenGiBnFMPj1VbFB3iKqq9rreAxK3EX6k1A3YF87XG+2o2DywVF+3NEZNxMaiQTjpRIYqalUhnV3XE25PXU3lR0TdeshX6iTqSuMF9VCv4s0wWPLThmqs="
    - secure: "GW55drx0g54pvRemitEHG4GAYarwikARPslYmcLUW4PVDFRJe05jcBUH1i789B1UJaVLPmD600/E/poxTUut6flA4PlPm1NiOx/ss9qyeXLOiGPYIk3USVkPfLWyKlvJOVNneX03/Z1fziWo6QLAbOmXPHPFGlI63yFt7zIEFYM="
    - secure: "RDAvH8wndF0IZhdzo9YUKZW6aHCFSObZJe8jpGIDytYHndFMgkV7Jw6qIaESXZ+ue+lt2/VM6p04r3MZ3+5kIXf3mtX+r1Wj/GX/foGRxQbs+E/AnzzL4ildjVTdNOqIQLWEBd7Nnd3mOegC6dHRneKF5EZXKpp+GoZr4OqgFQ8="
    - secure: "EdADmn+5us+K1uLOMFr0nxP26mMGTQDGGvNef0hjkLvaD595vyALCKjWapOQpW1ulJErDosW6QhUQSPlctjZ0y80oF8jg7RWb4tSfhJ2wpboNG8VddE49qNImx2wCy4Zp5mVHQ3sUuAaUH1czww94rDdo7evNw04XpjIMqiHLeM="
    - secure: "gpHfvnm7r96EXyOuOoiHSH8GaD/5UoBzHVPUnEIEgwZxQPzBbakiolEUhl2aKX/LtyN5r2xio7LTcmdM88vOEszrWG/PqT58AiNV/wdf+v8A+wdPMk5760de4Q2Z7B/xEalaYKQYX6hZgTKZHDbSqRhuYbswTGVhogUqlnDdTiU="
    - secure: "dO9Q4I1WMVduWSh7IsWP4oW65q4Qq4jGrRCqGSBB7faKNif0CBKEewyZwhVUMAcBVnPHed0FqbiFFC9xdzP7PShcvJ0tiv95s8foMAfEuL9QxvUshPn+5IR+zgRLsMxolxGuKioqeyBdPOdhKX/KCO6S4CjAEeGMXp134u8ZiM4="
    - secure: "R1w8DTohD3mOeEGv410kde8Timy3nWSPRe3CkSdB+SYsBSsSrcamKeo1wkahK6gkh9JPFZS09c+7TFYX8X4TGaYWjXq9r8wTQqw4fQNCboz2OMpU2ME48PVf6CAhADvQJodThpU/RgAzQ6zeZ5RvZQlhL4yblwdjDxBVmI8KELY="
    - secure: "lDrNRvb4NExcsquzeIbgrPQ5OAD2aovzQc8C/DosB236RQKFPtKaGxX8L6jOuU8H1UXgvf4DWVASykIU7xEPjAAPT4Si6kvQ2qCbpV3eq3FaF4m2mUs6NKHyTJOXJXHA3+oaR6tlLxJW5a09pFayFEENJNnlIXZiWNTiRA5EyZc="
    - secure: "h4EGDCp6LkJzF45sGfQZcLOGnlOrv3oAlzSvgBlGwbv2Q/C/b/2suyNJqNAuzg9YJCbq6B5dvfAtfleAUjD9iJJhFJePYRSaFviYK0lvHBIlFF2iXNq5vA28Yrnm9s+1v7WjjHoEsGKs7Au+sdw0FgM9esr+MmLZ01IhusYLIec="
    - secure: "J66Okh+NTY4u420qLkYZJWZMOEZpY3jJt20xKWhTHpbmSQnWZ95VHEBlSKsPx6IQ6gfiRBCG5ut2k9T/vALPml5RGRW9p2mzccG71ed3ZW0WfCy+YZxDXjLucijMVLSkpBPY9pKH7WdeJmIfpdIEL8jNj1ncnoSnURWRLoNz+qY="
    - secure: "mSEJAkEOohWW5VqCXA2LR9FqfC9EDPWpVK4wZz7MXidpFXvmuNVNiDySnDuWcaYb6E2APwqoEiqdOkhSuDM/HPDx/y1oFkgR1thHUJ3AFQ4TU++8SLezLtPvt4O510F0+R0qOFXxayLErY/eO5vaONjCQFX1E7vdMi/cquKWsPQ="
    - secure: "Hph2JOD2V5V0bNBhXsO1LwplKtWAhKH6/7BwbmMID9Ui4O7pdexMaizzGIW50SnnlmL8GxgUGpdWFJJqhOqG1HgOAbysRPIfv33m4Fhv/kYhAkfDH5ElODWlmhPGdpzawf9Hsol5G8UiAuhk43USvLeAzVpno860TA6b0towHlQ="
    - secure: "Mkw5R0UrEGIpCDQ6jEV2UVoKMiDeXd6mECfVusy9YzzOX94HRccp8dJYoL5qAx02qRRioGvOQUr525IxzUi0frrLOGF/K8XCW2iD5S7eynpTSgkHpa6opPuHssrpHA0YgAOxp1Nt4SRy2OXmeoixdr2Wt+/gWXnKKnCapTbhZyY="
    - secure: "ePOsoABJcwsXEQvi+WwE3uP21ZmfsQKdZqb/uqSoCreEG0tEaZ9NPxED1fwKBK0O29xnlgcRF2NWoJc9re/Qpy3ubGD+SqVa4trVW9eBlcussUgQRccf/zLsrDjxgJkJ2vi3jO+L510nVGo+pT9A3FdiUBfcKa9/PeAtZ0lVJpI="
    - secure: "NTYhWUj0Ol8eOjIeiW+MexsddEaRmhDUHrvvEgiY3w9v7j2UCorYSy9nif7lCR5yJof6syogOXxnaZSUxQFS/BRWuF15oyyjliv5ThsDg8v0xxUQLW0+ZydLuEetXuy0ZAAU51X6Fnh2MakMI80rRfecAM8s0hAQgw6DtbF1w3M="
    - secure: "W6xEIbLZY4HPSnt9yCAIlvrADf46WvJkG5608oNKA0kjhSLZXgqtrZpzPYT0lvzOybMgMlltb7P93HaMfGbbVVaOrzt5SybVQ2m/CV/aIcJbO3RrQvBtweRaMr+NvblTGGzd1HFtox3zGnNMyQiFiz2mGwbnc3JlwN1MAhJ6o5Q="
