markdown:         rdiscount
pygments:         true
paginate:         4

title:            Tech Talk - Git|Vim|RubyOnRails
url:              http://techtalk.everyday-cn.com
feed:             /atom.xml
author:
    name:         Tim.Tang
    email:        tang.jilong@gmail.com
description:      "Teck Talk v1.0 "

about: 			  "I am tim.tang love all kinds of design, attention to the Internet dynamic, dedicated web front development, learn UI and UED."
follow:
    github:       https://github.com/tim-tang
    twitter:      http://www.twitter.com/tangjilong
description:      "Teck Talk v1.0 "


style: 			  /css/style.css
blogName: 		  Tech Talk
blogDesc: 		  [Git|Vim|RubyOnRails]

layout:           default
comments:         true
