markdown:         rdiscount
pygments:         true
paginate:         6

title:            Tech Talk - Git|Vim|RubyOnRails
url:              http://tim.everyday-cn.com
feed:             /atom.xml
author:
    name:         Tim.Tang
    email:        tang.jilong@gmail.com
description:      "Teck Talk v1.1 "

about: 			  "Tim has about 5 years of experience doing end-to-end development of web applications for small startups and in the enterprise. In all contexts he strives to find simple, common-sense solutions to complex problems. Over the years he has worked with a wide variety of technologies.
Tim currently enjoys spending most of his time with RubyOnRails and jQuery but often has to find ways to coexist with legacy technologies for example J2EE in the IT department at a large enterprise.
Everyday&Tech Talk are two experimental websites for technic research and accumulate.
When not in front of a computer Tim enjoys spending time outdoors with his wife and little daughter or torturing himself by running long distances."
follow:
    github:       https://github.com/tim-tang
    twitter:      http://www.twitter.com/tangjilong
description:      "Teck Talk v1.0 "


style: 			  /css/style.css
blogName: 		  Tech Talk
blogDesc: 		  [Git|Vim|RubyOnRails]
